parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        types:
            datetime: CrosierSource\CrosierLibBaseBundle\Doctrine\Types\DefaultTimezoneDateTimeType
        connections:
            default:
                url: '%env(DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '8'
                mapping_types:
                    bit: boolean
                    enum: string
                    json: string
                default_table_options:
                    charset: 'utf8mb4'
                    collate: 'utf8mb4_unicode_ci'
            logs:
                url: '%env(DATABASE_LOGS_URL)%'
                driver: 'pdo_mysql'
                server_version: '8'
                mapping_types:
                    bit: boolean
                    enum: string
                    json: string
                default_table_options:
                    charset: 'utf8mb4'
                    collate: 'utf8mb4_unicode_ci'
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
            logs:
                connection: logs
                mappings:
                    CrosierSource\CrosierLibBaseBundle\Entity\Logs:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/vendor/crosiersource/crosierlib-base/src/Entity/Logs'
                        prefix: 'CrosierSource\CrosierLibBaseBundle\Entity\Logs'
                        alias: EntityLogs
                dql:
                    datetime_functions:
                        date_format: CrosierSource\CrosierLibBaseBundle\Doctrine\Extensions\MySQL\DateFormat
                        date: CrosierSource\CrosierLibBaseBundle\Doctrine\Extensions\MySQL\Date
                    string_functions:
                        JSON_UNQUOTE: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonUnquote
                        JSON_EXTRACT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonExtract
                        JSON_SEARCH: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonSearch
                        CAST: CrosierSource\CrosierLibBaseBundle\Doctrine\Extensions\MySQL\Cast
            default:
                connection: default
                auto_mapping: true
                mappings:
                    CrosierLibBaseBundle:
                        type: annotation
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                dql:
                    datetime_functions:
                        date_format: CrosierSource\CrosierLibBaseBundle\Doctrine\Extensions\MySQL\DateFormat
                        date: CrosierSource\CrosierLibBaseBundle\Doctrine\Extensions\MySQL\Date
                    string_functions:
                        JSON_UNQUOTE: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonUnquote
                        JSON_EXTRACT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonExtract
                        JSON_SEARCH: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonSearch
                        CAST: CrosierSource\CrosierLibBaseBundle\Doctrine\Extensions\MySQL\Cast
            
